### ISSUE TITLE
No Drupal 8 branch

### ISSUE THREAD

**Issue by drschwabe** [perusio/drupal-with-nginx#149]
There is currently no mention of D8 for those curious about running it with nginx,

**Comment by dandaka** [comment]
Maybe its good idea to put this into documentation?

**Comment by troubleshooter** [comment]
It's already in the README under Configuration Selection Algorithm.

**Comment by dandaka** [comment]
Hehe, thank you! My Cmd-F also wasn't working :)

**Comment by sint** [comment]
With the release of D8 later this month, will there be a D8 branch anyway?
