### ISSUE TITLE
nginx source package unavailable for recompilation?

### ISSUE THREAD

**Issue by arielsalvo** [perusio/drupal-with-nginx#196]
Hi,

Due to a security issue with people impersonating GoogleBot, I'm attempting to follow the instructions in http://debian.perusio.net/ to recompile your .deb package with the nginx-http-rdns 3rd party module.
The source package for nginx-1.7.7-perusio.1.0 seem to be unavailable.

```
# apt-get -t unstable -u source nginx
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Can not find version '1.7.7-perusio.1.0' of package 'nginx'
E: Unable to find a source package for nginx
```

Are you no longer distributing this package?

Thanks!
    --Ariel

**Comment by perusio** [comment]
Well it took sometime :( but it's done: https://github.com/perusio/nginx-debianization
