### ISSUE TITLE
Drupal 8 Support

### ISSUE THREAD

**Issue by guiajlopes** [perusio/drupal-with-nginx#233]
Hi everyone, I tried to use the D7 configuration on a D8 website  but sometimes I receive an error 502.

I think we should migrate the configuration for D8. Do you agree? I tested using drupal.conf file

Thanks

**Comment by perusio** [comment]
Yes, in the meantime, check this: https://github.com/perusio/drupal-with-nginx/issues/160

**Comment by guiajlopes** [comment]
I saw it, thanks @perusio I will reply on issue #160
